### ISSUE TITLE
The problem with the calculation of the path to the fonts

### ISSUE THREAD

**Issue by khusamov** [shutterstock/postcss-copy-assets#4]
I have a problem with file paths.

Gulp task:

``` javascript
gulp.task("css", function () {
    let src = ["bower_components/bootswatch/united/bootstrap.css"];
    gulp.src(src)
        .pipe(postcss([copyAssets({ base: "public/build" })], { to: "public/build/css/all.css" }))
        .pipe(concatCss("all.css"))
        .pipe(gulp.dest("public/build/css"));
});
```

At the entrance to the file:

**bower_components/bootswatch/united/bootstrap.css:**

``` css
@font-face {
    src: url('../fonts/glyphicons-halflings-regular.eot');
}
```

The output is a file with an error (wrong path):

**public/build/all.css:**

``` css
@font-face {
    src: url("../../bootswatch/fonts/glyphicons-halflings-regular.eot");
}
```

And here I should get the file:

``` css
@font-face {
    src: url("../../fonts/glyphicons-halflings-regular.eot");
}
```

How do I configure a task so that the path to the font correctly calculated?
